Run actions/setup-node@v4
Found in cache @ /opt/hostedtoolcache/node/20.19.4/x64
Environment details
/opt/hostedtoolcache/node/20.19.4/x64/bin/npm config get cache
/home/runner/.npm
Error: Some specified paths were not resolved, unable to cache dependencies.name: Deploy Frontend to GitHub Pages

on:
  push:
    branches: [main, feature/nestjs-backend]
    paths:
      - 'packages/frontend/**'
      - '.github/workflows/deploy.yml'
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-and-deploy:
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/feature/nestjs-backend'
    runs-on: ubuntu-latest

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    permissions:
      contents: read
      pages: write
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: 'packages/frontend/package.json'

      - name: Install dependencies
        run: |
          cd packages/frontend
          npm ci

      - name: Determine API URL
        id: api-config
        run: |
          if [ "${{ github.ref }}" == "refs/heads/main" ]; then
            echo "api_url=" >> $GITHUB_OUTPUT
            echo "branch_name=main" >> $GITHUB_OUTPUT
            echo "deployment_type=static" >> $GITHUB_OUTPUT
          elif [ "${{ github.ref }}" == "refs/heads/feature/nestjs-backend" ]; then
            echo "api_url=https://api.hsr-team-builder.gilded.dev" >> $GITHUB_OUTPUT
            echo "branch_name=feature-backend" >> $GITHUB_OUTPUT
            echo "deployment_type=api-enabled" >> $GITHUB_OUTPUT
          fi

      - name: Build frontend
        run: |
          cd packages/frontend
          echo "Building frontend for branch: ${{ steps.api-config.outputs.branch_name }}"
          echo "API URL: ${{ steps.api-config.outputs.api_url }}"
          echo "Deployment type: ${{ steps.api-config.outputs.deployment_type }}"
          npm run build
        env:
          VITE_API_URL: ${{ steps.api-config.outputs.api_url }}
          
      - name: Add branch info to build
        run: |
          echo "<!-- Deployed from branch: ${{ github.ref_name }} -->" >> packages/frontend/dist/index.html
          echo "<!-- API URL: ${{ steps.api-config.outputs.api_url }} -->" >> packages/frontend/dist/index.html
          echo "<!-- Deployment type: ${{ steps.api-config.outputs.deployment_type }} -->" >> packages/frontend/dist/index.html

      - name: Add cache headers via .htaccess
        run: |
          cat > packages/frontend/dist/.htaccess << 'EOF'
          # Cache static assets for 1 year
          <FilesMatch "\.(js|css|png|jpg|jpeg|gif|ico|svg|webp|woff|woff2|ttf|eot)$">
            Header set Cache-Control "public, max-age=31536000, immutable"
          </FilesMatch>

          # Cache HTML files for 1 hour
          <FilesMatch "\.(html)$">
            Header set Cache-Control "public, max-age=3600"
          </FilesMatch>

          # Enable gzip compression
          <IfModule mod_deflate.c>
            AddOutputFilterByType DEFLATE text/plain
            AddOutputFilterByType DEFLATE text/html
            AddOutputFilterByType DEFLATE text/xml
            AddOutputFilterByType DEFLATE text/css
            AddOutputFilterByType DEFLATE application/xml
            AddOutputFilterByType DEFLATE application/xhtml+xml
            AddOutputFilterByType DEFLATE application/rss+xml
            AddOutputFilterByType DEFLATE application/javascript
            AddOutputFilterByType DEFLATE application/x-javascript
          </IfModule>

          # Enable browser caching
          <IfModule mod_expires.c>
            ExpiresActive on
            ExpiresByType text/css "access plus 1 year"
            ExpiresByType application/javascript "access plus 1 year"
            ExpiresByType image/png "access plus 1 year"
            ExpiresByType image/jpg "access plus 1 year"
            ExpiresByType image/jpeg "access plus 1 year"
            ExpiresByType image/gif "access plus 1 year"
            ExpiresByType image/webp "access plus 1 year"
            ExpiresByType image/svg+xml "access plus 1 year"
            ExpiresByType application/font-woff "access plus 1 year"
            ExpiresByType application/font-woff2 "access plus 1 year"
          </IfModule>
          EOF

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './packages/frontend/dist'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
